### ISSUE TITLE
Urls build with IPiletService.GetUrl() are not correct.

### ISSUE THREAD

**Issue by luckyluggi** [FlorianRappl/Piral.Blazor#109]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [ x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [ x] Are you running the latest version?
- [ x] Did you perform a search in the issues?

## Environment Details and Version

[Package Version, Blazor Version, OS, Browser,...]

## Description
Image loaded from `wwwroot` via `IPiletService.GetUrl()` are not found.
I've reproduced the bug here:
https://github.com/luckyluggi/piral_extensions_and_aimages

## Steps to Reproduce

1. [First Step]
2. [next step...]

## Expected behavior

[What you expected to happen]

## Actual behavior

[What actually happened]

## Possible Origin / Solution

[Optionally, share your idea to fix the issue]

**Comment by FlorianRappl** [comment]
I think this is not an issue, however, I'd love to keep it open for now - maybe the issue with the images / assets in a referenced lib is there and then we can change / use this one.

**Comment by FlorianRappl** [comment]
Quick ping on this one: If there is an issue with assets coming from RCLs then we can track and fix it here.

cc @luckyluggi

**Comment by luckyluggi** [comment]
No, i think this can be closed.
