### ISSUE TITLE
Blazor Pilet Debugging - Pull in pilets within configured feed

### ISSUE THREAD

**Issue by MarioBolivar** [FlorianRappl/Piral.Blazor#111]
# New Feature Proposal

Would like to have a way to configure a feed to pull other enabled pilets from a configured feed during a specific Blazor pilets debug session. This could potentially be a parameter to somehow pass to Piral.Blazor.DevServer or via the devserver config directly. We see `npx pilet debug` has a `--feed` param but we are not able to hook into this as Piral.Blazor.DevServer abstracts the blazor pilet debug process,

![image](https://user-images.githubusercontent.com/43153798/217598239-2f91f35b-0dc8-40a7-95af-c2c19df64451.png)
ref: https://github.com/smapiot/piral/blob/main/docs/commands/debug-pilet.md#--feed

This would allow us to ensure pilets integrate together well during development workflows.

**Comment by FlorianRappl** [comment]
This works via a `feedUrl` parameter in the *blazor-devserversettings.json*.
