### ISSUE TITLE
Configuration Values (configured in the feed) should also be available when debugging.

### ISSUE THREAD

**Issue by luckyluggi** [FlorianRappl/Piral.Blazor#112]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description
The possibility to set configs in the feed service is great, but while running pilets locally via `pilet debug` the configs are currently empty. It would be great if they were also pulled if i add the feed via --feed.
Or even better if they could be configured in a json file just for running and debugging pilets localy.

## Background

[Provide any additional background for the feature, e.g., why is the current solution insufficient, what problem will it solve, etc.]

## Discussion

[Optionally, outline any pros and cons you can currently think of to provide the basis for a solid discussion]

**Comment by FlorianRappl** [comment]
> Or even better if they could be configured in a json file just for running and debugging pilets localy.

They can - via the `meta.json` (see https://github.com/smapiot/Piral.Blazor#overwriting-the-debug-meta-data).

The problem, in general, is that `--feed` is used to merge in the *other* pilets, i.e., the ones matching the same name as the debugged pilets are discarded. That being said, this implies that merging would actually discard the config for the locally debugged pilets.

What we could do is that we don't discard, but rather "overwrite" (deep merge). This way, we would keep locally non-specified configs (i.e., configs coming from the feed, from pilets that match the currently debugged pilets), while still overriding with values that are locally given, too.

**Comment by luckyluggi** [comment]
Okay, sorry, i've overlooked the possibility to add the meta.json file. That solves my problem.

**Comment by FlorianRappl** [comment]
With the `piral-cli` v0.15.8 there will be a new option for the pilet injector - `mergeConfig` (`true`/`false`). If set to `true` the config values (if existing) of a remote pilet will be merged / put into the local pilet metadata.
