### ISSUE TITLE
Generic Dependencies can not be resolved

### ISSUE THREAD

**Issue by luckyluggi** [FlorianRappl/Piral.Blazor#117]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

[Package Version, Blazor Version, OS, Browser,...]

## Description

If a generic dependecy is injected in a component (f.e.: `@inject CustomLogger<T> _customLogger`) it can not be resolved

## Steps to Reproduce

The issue can be reproduced with this example:
https://github.com/luckyluggi/piral_blazor_generic_deps

## Expected behavior

[What you expected to happen]

## Actual behavior

[What actually happened]

## Possible Origin / Solution

[Optionally, share your idea to fix the issue]

**Comment by FlorianRappl** [comment]
Caution: You cannot have a generic component! This is also explained in the README (https://github.com/smapiot/Piral.Blazor#components-tiles-menu-items-and-others).

**Comment by luckyluggi** [comment]
Ah yes sorry that was a bad example.
I removed the generic component, but the problem with the generic dependency still exists.
