### ISSUE TITLE
Leftover Node Processes After Terminated Debug Sessions

### ISSUE THREAD

**Issue by MarioBolivar** [FlorianRappl/Piral.Blazor#118]
# Bug Report

## Environment Details and Version
OS: Windows 10 version 22H2 (Build 19045.2728)
.NET 6
Piral.Blazor versions
- Piral.Blazor.DevServer 6.0.7
- Piral.Blazor.Utils 6.0.7
- Piral.Blazor.Tools 6.0.7

Browser: Chrome Version 111.0.5563.147

## Description

We are noticing lots of lingering/headless node processes after blazor pilets are terminated. They seem to not be getting cleaned up properly by the Piral.Blazor debugging utils and or Visual Studio. This seems to be locking the piral~/ directory and causing other issues around hot reload when modifying/updating scoped .razor.css files.

![image](https://user-images.githubusercontent.com/43153798/231523424-8fd0a908-79e1-4d39-9fe5-175e4dd0c6ac.png)

## Steps to Reproduce

1. Open task manager and observe no headless node instances
2. Open a sample Blazor pilet and run with debugging (F5) through the default IIS Express profile
3. Stop the debugging instance
4. Open task manager and observe the lingering headless node instances

## Expected behavior

Piral.Blazor debugging abstractions should cleanup any lingering resources when terminating a debugging session to ensure no headless node instances remain.

## Actual behavior

Piral.Blazor debugging abstractions are not cleaning up lingering resources when terminating a debugging session and are leaving behind headless node processes that are locking resources in piral~/ which causes hot reload issues in further debugging sessions as .razor and .razor.css files cannot be updated.

**Comment by MarioBolivar** [comment]
If you're experiencing this issue, the current workaround can be to manually kill any lingering and headless node processes prior to starting a new debugging instance to avoid hot reload issues.

**Comment by FlorianRappl** [comment]
This is fixed and will be part of 7.0.8.
