### ISSUE TITLE
Event listener is not removed

### ISSUE THREAD

**Issue by prepfarm** [FlorianRappl/Piral.Blazor#129]
# Bug Report

## Prerequisites

- [ x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [ x] Are you running the latest version?
- [x ] Did you perform a search in the issues?

## Environment Details and Version

piral 1.3.3
net7.0 with Piral.Blazor packages are 7.0.10-pre.20231128.2

## Description

`RemoveEventListener` Is not actually removing event listener. Trying out [this](https://github.com/smapiot/Piral.Blazor?tab=readme-ov-file#events) example inside of my project, is not getting removed and if component gets initialized again (go back and open the page again), number of logs always increases by one (I have added log inside of the `ToggleSidebar` method).

## Expected behavior

Event listener to be removed.

**Comment by FlorianRappl** [comment]
Are you sure that the dispose is called?

**Comment by prepfarm** [comment]
Yes, I have added `@implements IDisposable` and log inside of `Dispose` method which gets called few seconds after navigating off that page.

**Comment by FlorianRappl** [comment]
Alright thanks for the confirmation - I will look into it.

**Comment by FlorianRappl** [comment]
This is fixed and will be part of v10.
