### ISSUE TITLE
Duplicated config generation

### ISSUE THREAD

**Issue by fsdschmidt** [FlorianRappl/Piral.Blazor#130]
# Bug Report

Generation of package.json produces duplicated configurations.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

Piral.Blazor.Tools 7.0.9

## Description

Given a pilet project with package-overwrites.json of following content:

```
{
    "piletConfig": [
        "container1",
        {
            "PiletConfig": {
                "SubConfig": {
                    "Key": "Value"
                }
            }
        }
    ]
}
```

A package build generates package.json with above config. Unfortunately with any following build it appends the config again and again into package.json:

```
"piletConfig": [
        "container1",
        {
            "PiletConfig": {
                "SubConfig": {
                    "Key": "Value"
                }
            }
        },
        "container1",
        {
            "PiletConfig": {
                "SubConfig": {
                    "Key": "Value"
                }
            }
        }
    ]
```

## Steps to Reproduce

1. Create package-overwrites.json with version dependent and container config.
2. Build project.
3. Build project again.

## Expected behavior

Package.json contains overwritten config block only ones. Generation overwrites piletConfig block with any build.

## Actual behavior

Any build adds the contents of piletConfig block again. This leads to displaying issues inside feed-service UI. During feed-service publish and config import, feed-service imports version dependent key value pairs only ones. But it adds container reference multiple times (impossible with config ui). On the other hand when piral downloads feed info from feed-service it gets container values only ones, so in my opinion it’s just displaying issue in package.json and feed-service UI.

## Possible Origin / Solution

-

**Comment by FlorianRappl** [comment]
Thanks for the report this will be fixed with the v10.

**Comment by fsdschmidt** [comment]
👍

**Comment by FlorianRappl** [comment]
This is fixed in the v10.
