### ISSUE TITLE
SupplyParameterFromQuery Binding

### ISSUE THREAD

**Issue by xigoku** [FlorianRappl/Piral.Blazor#131]
# Bug Report

## Environment Details and Version

Piral 7.0.10
Win11
Chrome

## Description

    [Parameter]
    [SupplyParameterFromQuery(Name = "text")]
    public string Text { get; set; } = string.Empty;
    
    Did not work in Pilet.

## Steps to Reproduce

Minimal example in standalone pilet.
https://github.com/hoffmann-jan/Piral.Blazor/compare/blazor-7.0...query-param-minimal

1. call site with query parameter http://localhost:5000/counter?text=t

## Expected behavior

Property Text will set to "t".
UI will show "t".

## Actual behavior
Property is always null.

## Possible Origin / Solution

If there is already a solution, share it please.

**Comment by FlorianRappl** [comment]
What is `SupplyParameterFromQuery`? Honestly, this is not supported as routing is not done via Blazor - it is done by Piral. And Piral is using route parameters as designated (and documented, see `README`, https://github.com/smapiot/Piral.Blazor#routes).

Is this a feature request? Can you elaborate how / why you want to use it?

I keep it open for now (maybe we can change it to a feature request even though opening a new issue with a clear scope would be better).

**Comment by xigoku** [comment]
You know query parameters?

A query parameter is a component of a URL that follows the “?” symbol and is used to provide additional information to a web server. It consists of key-value pairs separated by “&”. For example, in the URL “example.com/search?text=piral”, “text” is the query parameter key, and “Pirat” is the corresponding value. Query parameters help customize and refine the content requested from the server.

Routing works fine. But I need to get the key value pairs from it.

The SupplyParameterFromQueryAttribute is the Blazor way of binding a query parameter to a property. It works on pages only.

In my opinion (Blazor centric), it is a basic feature, so I decided to open a bug ticket.

**Comment by FlorianRappl** [comment]
> You know query parameters?

Yes, I do. And my answer reflects that. Query parameters are not part of the path schema (see the example that I mentioned). You can always read out query parameters (there are specific classes in JS and therefore also Blazor to do this). The routing, however, is (as mentioned) not sensitive to this (and it should not be - query parameters are exactly that; they do not influence the specific page that is shown, but rather the functionality on that page).

As mentioned the routing is not done by Blazor, hence for binding routing parameters you'll need to use the Piral router; and this one does not have a field for it.

> In my opinion (Blazor centric), it is a basic feature, so I decided to open a bug ticket.

It is a basic feature and works as intended: You can read it out programmatically; but there is no binding support.

**Comment by xigoku** [comment]
Thank you very much for your lightning fast response.

I'll discuss it with my colleagues tomorrow.

**Comment by xigoku** [comment]
After discussion with our colleagues, we see a feature request here.

We already have a programmatic solution to the problem. If you want we can create a pull request.

In it we would suggest a `PiralQueryParameter`.

**Comment by FlorianRappl** [comment]
> We already have a programmatic solution to the problem. If you want we can create a pull request.

Sure - please go ahead! Thanks!

**Comment by ghost** [comment]
I've added a PR. 
But how to test the changes in Piral.Blazor.Core?

**Comment by FlorianRappl** [comment]
> But how to test the changes in Piral.Blazor.Core?

You build it and use it in a project, e.g., in the contained example project.

**Comment by ghost** [comment]
I can't manage to debug the modified Piral.Blazor.Core.dll.

The shell loads its version from npm and a local exchange does nothing.

How should I proceed?
