### ISSUE TITLE
Custom NpmRegistry: Sequence contains no elements

### ISSUE THREAD

**Issue by prepfarm** [FlorianRappl/Piral.Blazor#133]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

**net8.0**
**Piral.Blazor.x** 8.0.11

## Description
Unable to use private npm registry for installing the Piral instance.

## Steps to Reproduce

1. `$ dotnet new blazorpilet --piralInstance my-app-shell --npmRegistry https://xxx`
2. Adding .npmrc file (following Azure artifacts guide - works on Angular/React Pilets when installing Piral instance)
3. `$ dotnet run`

## Expected behavior

For Pilet to run and being accessible in browser.

## Actual behavior

Error: `.nuget/packages/piral.blazor.tools/8.0.11/build/Piral.Blazor.Tools.targets(26,9): error : Sequence contains no elements`

**Comment by alex-zyl** [comment]
A bit more context about the issue
1. Set `<PiralInstance>` to an existing instance that is published to a private npm registry (e.g. ADO)
2. Set `<NpmRegistry>` with the link to a private npm registry
3. Run build process

Console output
```
    [piral-cli] ≡ƒªï  piral-cli v1.4.3
1>        [piral-cli] - Preparing source and target ...
1>        [piral-cli] - Scaffolding new pilet in D:\Projects\blazorpilet\src\piral~\blazorpilet ...
1>        [piral-cli] - Setting up npm registry (https://private-registry/npm/registry/) ...
1>        [piral-cli] - Installing npm package my-app-shell@0.0.43 ...
1>        [piral-cli] Γ£û [0002] Could not install the package "my-app-shell@0.0.43" using npm. Make sure npm is correctly installed and accessible: Error: npm ERR! code E401
1>        [piral-cli] npm ERR! Unable to authenticate, your authentication token seems to be invalid.
1>        [piral-cli] npm ERR! To correct this please try logging in again with:
1>        [piral-cli] npm ERR!     npm login
1>        [piral-cli]
1>        [piral-cli] npm ERR! A complete log of this run can be found in: C:\Users\user\AppData\Local\npm-cache\_logs\2024-02-12T13_32_05_296Z-debug-0.log
1>        [piral-cli] npm ERR! code E401
1>        [piral-cli] npm ERR! Unable to authenticate, your authentication token seems to be invalid.
1>        [piral-cli] npm ERR! To correct this please try logging in again with:
1>        [piral-cli] npm ERR!     npm login
1>        [piral-cli]
1>        [piral-cli] npm ERR! A complete log of this run can be found in: C:\Users\user\AppData\Local\npm-cache\_logs\2024-02-12T13_32_05_296Z-debug-0.log
1>        [piral-cli] ≡ƒÉ¢  Find detailed descriptions at https://docs.piral.io/code/search
1>        [piral-cli]
1>        [piral-cli]
1>        C:\Users\user\.nuget\packages\piral.blazor.tools\7.0.12\build\Piral.Blazor.Tools.targets(26,9): warning : The provided command 'cmd.exe /c npx.cmd pilet new "my-app-shell@0.0.43" --registry "https://private-registry/npm/registry/" --bundler none --no-install' in 'D:\Projects\blazorpilet\..\piral~\blazorpilet' did not finish successfully. The process might be corrupted.
1>        Successfully updated 'package.json'.
```

The issue is caused by calling "npx pilet new ***' before copying `.npmrc`
