### ISSUE TITLE
Dynamic Propertybindig for Extensions

### ISSUE THREAD

**Issue by ghost** [FlorianRappl/Piral.Blazor#135]
# Proposal for a new feature

## Description

The Piral extension should get a one-way binding for parameters. Currently a parameter can only be set initially.

## Background

For the provision of dynamic content it is necessary to inform extensions about the change of context.

Example: Change of a selected entity
The ID of the entity was passed as a parameter.
The extension shows information about the entity.
After selecting another entity, its ID should now be transferred to the extension so that the extension displays its information.

## Discussion

Disadvantage
- Possible breaking change

Advantages
- Extension can be used much more flexibly
- Dynamic extensions
- more fun

**Comment by FlorianRappl** [comment]
Hm without an example it's hard to discuss. Extension parameters are dynamic - so Piral automatically updates the rendered extensions with updated values.

**Comment by FlorianRappl** [comment]
Any info on this? I'll close it for now, but feel free to add more info / provide an example such that we re-open the discussion.
