### ISSUE TITLE
Visual Studio Breakpoints Issue

### ISSUE THREAD

**Issue by tyler-pongratz** [FlorianRappl/Piral.Blazor#138]
# Bug Report

## Environment Details and Version

- Piral Version: 1.4.3
- Blazor Version: net8 / 8.0.11
- OS: Windows 10
- Browser: Chrome
- Node Version: v20.11.0
- Piral.Blazor: 8.0.11

## Description

In Visual Studio 2022, I am unable to hit a breakpoint using the example Pilet.

## Steps to Reproduce

1. Download the [8.0.11 release](https://github.com/smapiot/Piral.Blazor/archive/refs/tags/v8.0.11.zip).
1. After extracting the files, run the `run.ps1` file within the example directory using PowerShell.
1. Open the `Pilet.sln` within the example directory using Visual Studio 2022.
1. Place a breakpoint within the `CounterPage.razor` file.
1. `F5` to debug the Pilet within Visual Studio.
1. Once up, try browsing to the Counter Example and click the button.

## Expected behavior

Breakpoint should be hit within visual studio when the button is clicked.

## Actual behavior

Breakpoint is not hit and you see the following message within Visual Studio: `No Symbols have been loaded for this document`

**Comment by FlorianRappl** [comment]
Works for me. Make sure you have VS configured as it should be.

Also note that you should produce pdb files. Not sure what your exact set up is, but for me (and others) this just works out of the box.
