### ISSUE TITLE
link target blank handling

### ISSUE THREAD

**Issue by fsdschmidt** [FlorianRappl/Piral.Blazor#139]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

"blazor": "[7.0.12]"
"piral": "[1.5.0]"
"Piral.Blazor.*": Version="7.0.12"

## Description

We upgraded to latest net7.0 piral version, unfortunately target blank error still exists. 

Piral does not handle target attribute of links. It's impossible to navigate into new tab (_blank).  

## Steps to Reproduce

1. get example project of Piral.Blazor
2. add test cases with patch:

diff --git a/example/pilet/Pilet/Components/OtherPage.razor b/example/pilet/Pilet/Components/OtherPage.razor
index c66753c..73aa505 100644
--- a/example/pilet/Pilet/Components/OtherPage.razor
+++ b/example/pilet/Pilet/Components/OtherPage.razor
@@ -11,8 +11,9 @@
 else
 {
     <div>
-    The Id was not read from the url.
-    <a href="/other/single/12345">Go to URL with parameter 12345</a>
+    The Id was not read from the url.<br/>
+    <a href="/other/single/12345" target="_blank">Go to relative URL inside new tab with parameter 12345</a><br/>
+    <a href="http://localhost:1234/other/single/12345" target="_blank">Go to absolute URL inside new tab with parameter 12345</a>
 </div>
 }

3. execute `example/run.sh` or `example/run.ps1`
4. after build, open `http://localhost:1234/other` in browser
5. try relative link
6. try absolute link

## Expected behavior

Relative and absolute link opens up inside new browser tab.

## Actual behavior

1. Relatives url's with target="_blank" opens inside current tab.
2. Absolute url's with target="_blank" also opens in current tab and link does not work, because absolute url is prefixed with piral base path (http://localhost:1234/http://localhost:1234/other/single/12345).

## Possible Origin / Solution

--

**Comment by FlorianRappl** [comment]
Thanks for reporting.

This will be fixed with `piral-blazor` 1.5.1. A preview of this is about to be released (currently building).

**Comment by fsdschmidt** [comment]
Thanks for fast fixing! With 1.5.1-beta.6852 target blank works.
