### ISSUE TITLE
Pilet start from IDE broken

### ISSUE THREAD

**Issue by fsdschmidt** [FlorianRappl/Piral.Blazor#140]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

"blazor": "[7.0.12]"
"piral": "[1.5.1]"
"Piral.Blazor.*": Version="7.0.12"

## Description

With latest piral and piral blazor version, a pilet start right from IDE results in feed request at launchSettings port.

## Steps to Reproduce

1. get example project of Piral.Blazor
2. execute example/run.sh or example/run.ps1 to build up whole environment
3. open example/pilet/Pilet.sln in IDE
4. build and run or debug project
5. browser opens at port 5231 with request "Specify Feed Source" (also with configured feed in blazor-devserversettings.json)

## Expected behavior

Browser shows shell with loaded Pilet at port 5231.

## Actual behavior

With launchSettings configured port 5231 piral ignores configured feed url. But at random service port (🚀  Running at http://localhost:52818) all is fine. 

## Possible Origin / Solution

--

**Comment by FlorianRappl** [comment]
This is fixed in the latest preview.
