### ISSUE TITLE
Add support for the @layout attribute and nested routes

### ISSUE THREAD

**Issue by luckyluggi** [FlorianRappl/Piral.Blazor#141]
# New Feature Proposal

Please add support for the @layout attribute and nested routes

## Description

I have created a demo blazor project as a working exmple. 
In a second project i converted it to a pilet where it currently does not work.

You can see the example here:
https://github.com/luckyluggi/piral_nested_layouts

**Comment by FlorianRappl** [comment]
This is now in the blazor-7.0 branch and part of the preview.
