### ISSUE TITLE
Debugging of Referenced Project Assemblies

### ISSUE THREAD

**Issue by FlorianRappl** [FlorianRappl/Piral.Blazor#143]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

Blazor v14, MacOS or Windows, Piral latest (1.5.3)

## Description

As explained in #142 the symbols for dependencies (if available) are not loaded.

Without the symbols the content of related libs cannot be debugged.

## Steps to Reproduce

1. See #142

## Expected behavior

If available the `.pdb` files are loaded.

## Actual behavior

No `.pdb` files are loaded (except the one from the pilet).

## Possible Origin / Solution

Check for dependency on ".dll" (which might be ".wasm") to get a pdb name.

**Comment by fsdschmidt** [comment]
With `8.0.15-pre.20240412.3` DesignSystem pdb loads in example solution, breakpoint in `ConsoleMessageService.LogMessageToConsole()` works again and also inside our solutions breakpoints of dependent assemblies working again. 👍 

Looking forward for 8.0.15 release.

**Comment by fsdschmidt** [comment]
With `8.0.15-pre.20240412.3` DesignSystem pdb of example solution loads, `ConsoleMessageService.LogMessageToConsole()` breakpoint works again and also inside our solutions breakpoints of dependent projects work again. 👍 

Looking forward to 8.0.15 release.

![Bildschirmfoto 2024-04-15 um 08 24 31](https://github.com/smapiot/Piral.Blazor/assets/43231196/f44b35c8-9ba3-44e7-8937-61df6b5d0b75)
