### ISSUE TITLE
Since upgrade to .NET 8 localization is broken

### ISSUE THREAD

**Issue by xigoku** [FlorianRappl/Piral.Blazor#144]
# Bug Report

## Prerequisites

- [x] MWE is /example, branch blazor-8.0
- [x] Are you running the latest version? Yes
- [x] Did you perform a search in the issues?

## Environment Details and Version

[Package Version, Blazor Version, OS, Browser,...]
- macOS Version 14.4.1 (23E224)
- Chrome Version 124.0.6367.78 (Official Build) (arm64)
- dotnet 8.0.204

## Description

Since .NET 8 resources are build into <project>.resources.wasm files. These files are missing in Browser "404 - FIle not Found".

## Steps to Reproduce

1. In Example run run-script
2. Switch Browser language to german or spanish
3. open counter page

## Expected behavior

if browser language german => Hallo Welt!
if browser language spanish => Hola Mundo!

## Actual behavior

always english text is rendered
![counter](https://github.com/smapiot/Piral.Blazor/assets/34597495/49b82307-491b-4768-b32f-23eda63b1675)

## Possible Origin / Solution

![error](https://github.com/smapiot/Piral.Blazor/assets/34597495/44e500eb-2f32-4e3f-9f36-4d8c7e954d25)

Maybe [here](https://github.com/smapiot/Piral.Blazor/commit/84163e8c1bc891d66ad819d8345e999a060be606) should a case for *.resources.wasm files be added.

Unfortunately can I not debug this library and so I can't contribute.

**Comment by FlorianRappl** [comment]
A fix for this is out in the latest preview ([8.0.16-pre.20240430.1](https://www.nuget.org/packages/Piral.Blazor.Core/8.0.16-pre.20240430.1)). Can you try if this works for you? Thanks!

**Comment by xigoku** [comment]
This solution works for me. Great job! Nice development speed :D
