### ISSUE TITLE
Rerendering extensions when parameters change

### ISSUE THREAD

**Issue by luckyluggi** [FlorianRappl/Piral.Blazor#145]
We can pass Parameters to the <Extension /> component and they get inserted into every extension loaded into the slot.
When these Parameters change in the top component the component does not reload.

I know that i could inform the extension-components about any changes via events, but it would be much more convenient if the component could get informed and update itself automatically.

I have created an example project here:
https://github.com/luckyluggi/piral_example_for_multiple_issues

Open the `/shop` page and toggle the "switch"-button in the topbar. 
This changes the boolean value in `LayoutPilet\Components\Topbar.razor` on line 23.
The value is passed to the Cart Extensions in the Topbar.Right extension-slot, but they are not updatet when this value changes.
To see a working example you can start the standard Blazor App `BlazorApp\BlazorApp.csproj`.

Do you see any chance this could be improved?

**Comment by FlorianRappl** [comment]
This is now shipped in the previews of `blazor` (v17) and `piral-blazor` (1.6.0).

**Comment by luckyluggi** [comment]
Thanks! I have tested it and it works 👍
