### ISSUE TITLE
Piral Extension Components do not render when used inside MudDialog

### ISSUE THREAD

**Issue by luckyluggi** [FlorianRappl/Piral.Blazor#147]
Piral extensions are not rendered inside a MudBlazor MudDialog Component.

The problem can be reproduced here:
https://github.com/luckyluggi/piral_net8_extensions

I think this might be because `<MudDialogProvider />` is included in a `[PiralProvider]`-Component.

**Comment by FlorianRappl** [comment]
I don't know yet when I can have a look at this.

My assumption is that this needs to be addressed in `piral-blazor`.

**Comment by FlorianRappl** [comment]
The assumption is correct. Will be fixed in `piral-blazor` at version 1.6.0.
