### ISSUE TITLE
Scaffolding check always passing

### ISSUE THREAD

**Issue by DanteDeRuwe** [FlorianRappl/Piral.Blazor#41]
Related to PR #38 

afaik the `_piletFolderPath` already has the `MSBuildProjectName` included, so it should already be considered when scaffolding. This being merged now includes the project name twice (e.g. `piral~/projectname/projectname`) and results in the scaffold always happening.

_Originally posted by @DanteDeRuwe in https://github.com/smapiot/Piral.Blazor/issues/38#issuecomment-844217803_

Reposted here to get opinion of @FlorianRappl about this

**Comment by FlorianRappl** [comment]
OK then let's undo!
