### ISSUE TITLE
Piral.Blazor 5 (and 6..)

### ISSUE THREAD

**Issue by davidnajar** [FlorianRappl/Piral.Blazor#48]
Currently version 3.2.1 is released, 5 is in prerelease and there isn't anything for dotnet6 blazor. Will eventually 5 and 6 be released? 
By the way, amazing work!

**Comment by FlorianRappl** [comment]
Yeah great point. Actually, its on my Christmas list (seriously).

**Comment by davidnajar** [comment]
I've added a PR. I've only updated project  targets and nuget refs to dotnet 6. Don't know if its enough

**Comment by FlorianRappl** [comment]
I think it should be (at least to get started with). I guess with Blazor 6 there may be more things to use / make use of (e.g., blazor components could now be registered as web components, too, which would make it easier to render them somewhere).

**Comment by davidnajar** [comment]
Maybe at build time we can generate a react component like in the official  [sample](https://github.com/aspnet/samples/blob/main/samples/aspnetcore/blazor/JSComponentGeneration/JSComponentGeneration.Build/React/GenerateReactComponents.cs). Will this be the proper approach? I can have a look on this

**Comment by FlorianRappl** [comment]
Yeah - I mean these build-time tasks we should anyway look into (thanks for linking that). This may be great for the dev experience. Generally, it maybe could be either an addition or even replacement to the codegen.

**Comment by FlorianRappl** [comment]
All released now!
