### ISSUE TITLE
Blazor Calling Extensions won't pass the Params correctly

### ISSUE THREAD

**Issue by jozsefkovacs** [FlorianRappl/Piral.Blazor#52]
In the sample:
https://github.com/smapiot/Piral.Blazor/blob/blazor-5.0/example/pilet/Pilet/Components/SampleExtension.razor

the `react-counter` is called with params `new { count = 10, diff = 3 }` however upon loading the page the starting value is 0 and the increment is 1, so the props have the default value.

![image](https://user-images.githubusercontent.com/24807920/149089741-9eb7b565-ab23-4894-a51e-a21815b1d5bd.png)

Adding a `console.log(params);` to the `react-counter` extension shows that the `params` is not undefined, but empty and have no properties.
![image](https://user-images.githubusercontent.com/24807920/149090000-199cc4c8-bd78-4f7e-8322-c2059f9a7443.png)

So calling Extensions from Blazor with Params, the Params is not correctly passed through.
Calling a Blazor Extension from React works.

**Comment by FlorianRappl** [comment]
Sorry for the confusion. This works with 0.14.7 of `piral-blazor` (or the preview of it).
