### ISSUE TITLE
Scaffolding on MacOS / nix breaks `blazor.codegen`

### ISSUE THREAD

**Issue by FlorianRappl** [FlorianRappl/Piral.Blazor#72]
When doing this on a non-Windows system the `blazor.codegen` has slashes (`/`)  everywhere where backslashes ( `\`) have been used. This breaks the code as regular expressions (and other things) suddenly become invalid syntax.

**Comment by FlorianRappl** [comment]
This seems to be related to a bug in msbuild: https://github.com/dotnet/msbuild/issues/3468

**Comment by lonix1** [comment]
Did you maybe find a workaround for that bug?
