### ISSUE TITLE
Update documentation with all possible Piral/Pilet related variables

### ISSUE THREAD

**Issue by jozsefkovacs** [FlorianRappl/Piral.Blazor#75]
I would like to have a list of possible variables listed in a document for the blazor project.cs.

e.g.: 
PiralInstanceVersion what it does how to use it
PiralInstance
NpmRegistry
etc.

Currently, I can't find a comprehensive list of vars supported.

**Comment by FlorianRappl** [comment]
Yeah that would be awesome - do you want to contribute that to the README.md?

**Comment by FlorianRappl** [comment]
I've added a section - is this what you had in mind?

https://github.com/smapiot/Piral.Blazor#build-configuration

**Comment by jozsefkovacs** [comment]
Yes, indeed.

I see other Tasks existing and are actually offering cool interaction with package.json for example:
if Version is set, it will declare in the piral~ folder package.json the Pilet version.
https://github.com/smapiot/Piral.Blazor/blob/c2afb1478f6d727c71b8b112e19205c74d2787d3/src/Piral.Blazor.Tools/tasks/SetProjectJsonVersionTask.cs

also, I wonder what this does and how to use it:
https://github.com/smapiot/Piral.Blazor/blob/c2afb1478f6d727c71b8b112e19205c74d2787d3/src/Piral.Blazor.Tools/tasks/AddProjectJsonOverwritesTask.cs

**Comment by FlorianRappl** [comment]
Yeah I think these would be also great additions to the documentation.

- Include `<Version>` to set / modify the version of the pilet (and align it of course with the Blazor code base / csproj)
- The meaning of the different files,  `overwrite.package.json`, `setup.tsx`, and `Module.cs` (the latter two have been briefly touched, but they should be discussed explicitly)

Mind creating issues for these two (and anything else that is on your mind)? Then we can track that for `v2`.

Thanks @jozsefkovacs !

**Comment by jozsefkovacs** [comment]
raised #76 and #77 
I'll look around and try to come up with more issues ;)

Thanks for the quick modifications!
