### ISSUE TITLE
Calling StateHasChanged() does not reload Page and Extension Components

### ISSUE THREAD

**Issue by luckyluggi** [FlorianRappl/Piral.Blazor#88]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

[Package Version, Blazor Version, OS, Browser,...]

## Description

Hy. I've been tracking down a problem in my app and i think i've found the source of the problem now.
I have created this mvp to show the problem:
https://github.com/luckyluggi/-mvp_piral_statehaschanged

There i have a StateContainer (my-pilet\State\ShoppingCartState.cs) with Items.
Whenever i add items i call StateHasChanged() in my-pilet\Pages\ShopPage.razor and my-pilet\Components\ShoppingCartIcon.razor but the state does not get updated.

## Steps to Reproduce

see mvp

## Expected behavior

Component should reload and show new state

## Actual behavior

does not reload

## Possible Origin / Solution

[Optionally, share your idea to fix the issue]

**Comment by FlorianRappl** [comment]
Actually the `StateHasChanged` works fine.

The problem is in the event handler. If you disable the first handler (just comment out the one in `Shop` you'll see everything updates (except the `Shop`). I'll investigate this.

**Comment by FlorianRappl** [comment]
Alright so changing the service from `AddScoped` to `AddSingleton` did the job. From official documentation:

> Scoped objects are the same within a request, but different across different requests.

Apparently, we had different requests beforehand. We've seen two objects being created.

> Singleton objects are the same for every object and every request.

Now we force it to be the same. And it works.
