### ISSUE TITLE
Moving to another route using NavigationManager.NavigateTo() is rurrently not possible

### ISSUE THREAD

**Issue by luckyluggi** [FlorianRappl/Piral.Blazor#89]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

[Package Version, Blazor Version, OS, Browser,...]

## Description

When i want to move to another page programmatically by injecting "Navigationmanager" and calling "_navigationManager.NavigateTo($"/item/create");" the page does not change.
I can ofcourse add true as a second param to bypass client side routing and load the new page from the server, and it does work, but that's not rly nice and slow.

I've added an example page to the mvp (/navigationmanager):
https://github.com/luckyluggi/mvp_piral_route_params

More info on Navigationmanager:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.navigationmanager.navigateto?view=aspnetcore-6.0

## Steps to Reproduce

see mvp

## Expected behavior

should move to another route

## Actual behavior

does not move to another route

## Possible Origin / Solution

[Optionally, share your idea to fix the issue]

**Comment by FlorianRappl** [comment]
This can be fixed by an update of `piral-blazor` (incoming 0.14.28).
