### ISSUE TITLE
NavLink active class does not get updated and NavigationManager.LocationChanged is not called.

### ISSUE THREAD

**Issue by luckyluggi** [FlorianRappl/Piral.Blazor#92]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Description
If you switch Change Routes in the app the `active` class in <NavLink /> Components is not updated.
Also NavigationManager.LocationChanged does not get called.

## Steps to Reproduce
I Have created an MVP to make this clearer.
https://github.com/luckyluggi/mvp_route_update

**Comment by FlorianRappl** [comment]
This is an issue of `piral-blazor` and will be fixed in 0.15. It's already available in the preview.
