### ISSUE TITLE
It should be configurable where the piral~ folder is created

### ISSUE THREAD

**Issue by luckyluggi** [FlorianRappl/Piral.Blazor#94]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

Currentl the folder is created one directory up. We would like to configure it to be 2 directories up.

## Background

[Provide any additional background for the feature, e.g., why is the current solution insufficient, what problem will it solve, etc.]

## Discussion

[Optionally, outline any pros and cons you can currently think of to provide the basis for a solid discussion]

**Comment by FlorianRappl** [comment]
It's in - configuration is called `OutputFolder`.
