### ISSUE TITLE
The Browser Window does a hard reload when navigating to an upper route.

### ISSUE THREAD

**Issue by luckyluggi** [FlorianRappl/Piral.Blazor#96]
# Bug Report

For more information, see the `CONTRIBUTING` guide.

## Prerequisites

- [ ] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [ ] Are you running the latest version?
- [ ] Did you perform a search in the issues?

## Environment Details and Version

[Package Version, Blazor Version, OS, Browser,...]

## Description
I've created an mvp showing the problem:
https://github.com/luckyluggi/mvp_route_reload

When you enter the root Page you can switch between all pages using the buttons at the top like it should be. In this case `<base href="http://localhost:1234/">` is set in the <head>.

But if you go to http://localhost:1234/winter/posts and press F5 -> `<base href="http://localhost:1234/winter/posts">` gets written into the `<head>`. Now you can switch between all /winter/*-Pages like it should be, but as soon as you switch to a /summer/*-Page the browser window reloads.

I belive it has something to do with the `<base>`.

## Steps to Reproduce

1. [First Step]
2. [next step...]

## Expected behavior

[What you expected to happen]

## Actual behavior

[What actually happened]

## Possible Origin / Solution

[Optionally, share your idea to fix the issue]

**Comment by FlorianRappl** [comment]
This is solved with the 0.15.0 of `piral-blazor`.
