### ISSUE TITLE
Pilets should be able to add to App.razor

### ISSUE THREAD

**Issue by luckyluggi** [FlorianRappl/Piral.Blazor#97]
# New Feature Proposal

For more information, see the `CONTRIBUTING` guide.

## Description

Currently the App. razor file is locked away and has to be taken as it is.
If f.e. `Microsoft.AspNetCore.Components.Authorization` should be used The App.razor must be edited like this:
``` html
<CascadingAuthenticationState>
    <Router ...>
        <Found ...>
            <AuthorizeRouteView RouteData="@routeData" 
                DefaultLayout="@typeof(MainLayout)" />
        </Found>
        <NotFound>
            <LayoutView ...>
                ...
            </LayoutView>
        </NotFound>
    </Router>
</CascadingAuthenticationState>
```

This should be possible.

## Background

[Provide any additional background for the feature, e.g., why is the current solution insufficient, what problem will it solve, etc.]

## Discussion

[Optionally, outline any pros and cons you can currently think of to provide the basis for a solid discussion]

**Comment by FlorianRappl** [comment]
As Blazor does not host the router the `AuthorizeRouteView` cannot be used like that, however, the top-level component (`CascadingAuthenticationState`) can be introduced. The only question is - should this be placed on top for all components or just for some (e.g., the ones contained in the same pilet)?

Right now leaning towards a solution that makes it only available for components in the same pilet. Otherwise you'd get inconsistencies, e.g., when one blazor pilet (DLL) is loaded before or after the other.

**Comment by FlorianRappl** [comment]
Alright we now have a solution that allows specifying a special component using the `PiralAppRoot` attribute (as opposed to, e.g., `PiralComponent` attribute). A component with this attribute will be placed as the app root's component, e.g., it could look like

```razor
@attribute [PiralAppRoot]

<CascadingAuthenticationState>
    @ChildContent
</CascadingAuthenticationState>

@code {
  [Parameter]
  public RenderFragment ChildContent { get; set; }
}
```

Again, note that only one of these is taken at a time, so make sure to choose wisely.

**Comment by FlorianRappl** [comment]
Alright this is working.

Example:

```razor
@attribute [PiralAppRoot]

<CascadingValue Value="@theme">
    <div>
        @ChildContent
    </div>
</CascadingValue>

@code {
    [Parameter]
    public RenderFragment ChildContent { get; set; }
    
    private string theme = "dark";
}
```

where in some component

```razor
<h1>Shop for @ThemeInfo</h1>

@code{
    [CascadingParameter]
    protected string ThemeInfo { get; set; }
}
```

values are properly cascading, everything else is properly appended.
